apiVersion: v1
kind: Pod
metadata:
  labels:
    run: balancer
    name: haproxy
    app: haproxy
  name: haproxy
spec:
  containers:
  - image: haproxytech/haproxy-alpine:3.0
    name: haproxy 
    ports:
      - containerPort: 80
      - containerPort: 443
    resources: 
      limits:
        cpu: "1"
        memory: "246Mi"
      requests:
        cpu: "1"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
