apiVersion: v1 
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx 
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-volume-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-volume-emptydir
    emptyDir:
      sizeLimit: 256Mi
